# Generated by Django 3.1.6 on 2022-01-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('L', 'Living'), ('B', 'Bedroom'), ('D', 'Dining'), ('S', 'Storage'), ('ST', 'Study'), ('DE', 'Decor')], max_length=2)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
    ]
